setw -g mode-keys vi

# Setup 'v' to begin selection, just like Vim
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Setup 'y' to yank (copy), just like Vim
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Update the default binding of 'Enter' to use copy-selection-and-cancel
unbind-key -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-selection-and-cancel

# Reduce delay when pressing Escape in Vim
set -sg escape-time 10

# List of plugins
set -g @plugin "tmux-plugins/tmux-sensible"

set -g @resurrect-processes "pomo btm cliamp"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run 'tpack init'
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin "tmux-plugins/tmux-resurrect"
