setw -g mode-keys vi

# Setup 'v' to begin selection, just like Vim
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Setup 'y' to yank (copy), just like Vim
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Update the default binding of 'Enter' to use copy-selection-and-cancel
unbind-key -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-selection-and-cancel

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.config/tmux/tmux.conf

# Start windows and panes at 1
set -g base-index 1
setw -g pane-base-index 1

# switch panes using Alt plus vi motion without prefix
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-j select-pane -U
bind -n M-k select-pane -D

# Reduce delay when pressing Escape in Vim
set -sg escape-time 10

# List of plugins
set -g @plugin "tmux-plugins/tmux-sensible"

set -g @resurrect-processes "pomo btm cliamp"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run 'tpack init'
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "erikw/tmux-powerline"
